#!/usr/bin/env python

CMD_PATTERN = 'emrichen -f config.yaml -f iana.yaml %s -o %s --output-format %s %s'

def parseFilename(filepath):
    import os.path
    filename = os.path.basename(filepath)
    pieces = filename.split('.')
    assert len(pieces) > 2
    fhead = pieces[0]
    fname = pieces[1]
    ffeatures = pieces[2:-1]
    ftype = pieces[-1]
    assert fhead == 'message'
    assert ftype in ['json', 'yml', 'yaml']
    ftemplate = '%s.%s.yaml' % (fhead, fname)
    fvars = ' '.join(['-D %s=true' % f for f in ffeatures])
    return CMD_PATTERN % (fvars, filepath, ftype, ftemplate)

if __name__ == '__main__':
    import sys
    if len(sys.argv) < 2:
        usage("Usage: %s <PATH_TO_GENERATED_SCHEMA>" % (sys.argv[0]))
        sys.exit(0)
    print(parseFilename(sys.argv[1]))

